import './globals.css'
import Head from 'next/head'
import Navbar from '@/Components/Navbar/Navbar'


export const metadata = {
  title: 'IEEE STB',
  description: 'Generated by create next app',
  image:'/app/HomePageUtils/favicon.png'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
      <meta property="og:image" content={metadata.image} />
    </Head>
    <body>
    <Navbar/>
      {children}
      </body>
  </html>
  )
}
