import './globals.css'
import Head from 'next/head'
import Navbar from '@/Components/Navbar/Navbar'


export const metadata = {
  title: 'IEEE STB',
  description: 'Generated by create next app',
  image:""
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
      <meta property="image" content={metadata.image} />
    </Head>
    <body className="w-[100%] bg-primary">
      <div className="text-tertiary max-w-[80%] mx-[10%]  md:mx-[10%] lg:mx-[10%]">
    <Navbar/>
      {children}
      </div>
      </body>
  </html>
  )
}
