import './globals.css'
import Head from 'next/head'
import Navbar from '@/Components/Navbar/Navbar'
import Footer from '@/Components/Footer/Footer'
import ScrollToTopButton from '@/Components/ScrollToTop'


export const metadata = {
  title: 'IEEE STB',
  description: 'Generated by create next app',
  image:""
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
      <meta property="image" content={metadata.image} />
    </Head>
    <body className=" bg-primary ml-[5%] mr-[3%] lg:mx-[5%]">
    <Navbar/>
      {children}
      <ScrollToTopButton/>
    <Footer/>
      </body>
  </html>
  )
}
